# Generated by Django 4.2.21 on 2025-12-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0095_fix_related_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrameLogitMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame", models.PositiveIntegerField()),
                ("relative_path", models.CharField(max_length=1024)),
                ("mime_type", models.CharField(default="image/png", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frame_logits",
                        related_query_name="frame_logit",
                        to="engine.job",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("job", "frame")},
            },
        ),
    ]










