# Generated by Django 4.2.25 on 2025-12-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0096_framelogitmeta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="framelogitmeta",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
