# Generated by Django 4.2.25 on 2025-12-24 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0097_alter_framelogitmeta_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrameLogit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("frame", models.PositiveIntegerField()),
                ("data", models.BinaryField()),
                ("dtype", models.CharField(default="float32", max_length=32)),
                ("compression", models.CharField(default="png_16bit", max_length=32)),
                ("width", models.PositiveSmallIntegerField()),
                ("height", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logits",
                        related_query_name="logit",
                        to="engine.job",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("job", "frame")},
            },
        ),
    ]
